[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "palmerpenguins>=0.1.4",
    "plotnine>=0.15.0",
    "shiny>=1.5.0",
]
